-- MySQL Script generated by MySQL Workbench
-- Tue Oct 11 20:21:46 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema team_celular
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema team_celular
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `team_celular` DEFAULT CHARACTER SET utf8 ;
USE `team_celular` ;

-- -----------------------------------------------------
-- Table `team_celular`.`user_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team_celular`.`user_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NOT NULL,
  `create_date` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `team_celular`.`user_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team_celular`.`user_status` (
  `iduser_status` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`iduser_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `team_celular`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team_celular`.`Users` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `user_category` INT NOT NULL,
  `create_date` VARCHAR(45) NOT NULL,
  `status` INT NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `profile_image` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `category_idx` (`user_category` ASC) VISIBLE,
  INDEX `status_idx` (`status` ASC) VISIBLE,
  CONSTRAINT `category`
    FOREIGN KEY (`user_category`)
    REFERENCES `team_celular`.`user_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `status`
    FOREIGN KEY (`status`)
    REFERENCES `team_celular`.`user_status` (`iduser_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `team_celular`.`products_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team_celular`.`products_category` (
  `idcategory` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `active` VARCHAR(45) BINARY NULL,
  PRIMARY KEY (`idcategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `team_celular`.`products_brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team_celular`.`products_brand` (
  `id_brand` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_brand`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `team_celular`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team_celular`.`products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `stock` INT NOT NULL,
  `product_code` VARCHAR(45) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `active` INT NOT NULL,
  `category` INT NOT NULL,
  `brand` INT NOT NULL,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `product_code_UNIQUE` (`product_code` ASC) VISIBLE,
  INDEX `category_idx` (`category` ASC) VISIBLE,
  INDEX `brand_idx` (`brand` ASC) VISIBLE,
  CONSTRAINT `category`
    FOREIGN KEY (`category`)
    REFERENCES `team_celular`.`products_category` (`idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `brand`
    FOREIGN KEY (`brand`)
    REFERENCES `team_celular`.`products_brand` (`id_brand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `team_celular`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team_celular`.`orders` (
  `order_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `order_adress` VARCHAR(45) NOT NULL,
  `order_date` DATE NOT NULL,
  `order_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `user id_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `user id`
    FOREIGN KEY (`users_id`)
    REFERENCES `team_celular`.`Users` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `team_celular`.`order_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team_celular`.`order_details` (
  `order_details_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `total_price` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`order_details_id`),
  INDEX `order_idx` (`order_id` ASC) VISIBLE,
  INDEX `product_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `order`
    FOREIGN KEY (`order_id`)
    REFERENCES `team_celular`.`orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product`
    FOREIGN KEY (`product_id`)
    REFERENCES `team_celular`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
